export const Column = [
  {
    field: "full_name",
    headerName: "Full name",
    disableColumnMenu: true,
    sortable: true,
    width: "100%",
    type: "string",
    minWidth: 200,
    flex: 1,
  },
  {
    field: "date_of_birth",
    headerName: "Birthday",
    disableColumnMenu: true,
    sortable: true,
    type: "string",
    width: "auto",
    minWidth: 200,
    flex: 1,
  },
  {
    field: "email",
    headerName: "Email",
    disableColumnMenu: true,
    sortable: true,
    type: "email",
    width: "auto",
    minWidth: 200,
    flex: 1,
  },
  {
    field: "department",
    headerName: "Department",
    disableColumnMenu: true,
    sortable: true,
    type: "string",
    width: "auto",
    minWidth: 200,
    flex: 1,
  },
  {
    field: "role",
    headerName: "Role",
    disableColumnMenu: true,
    sortable: true,
    width: "auto",
    minWidth: 200,
    flex: 1,
  },
];
